@startuml

title __EXP's Class Diagram__\n

  namespace rerank.cred {
    namespace exp {
      class rerank.cred.exp.CMeasurer {
          ~ credScore : HashMap<String, Double>
          ~ imageUser : HashMap<String, String>
          ~ rankScore : HashMap<String, Double>
          ~ useRankScore : boolean
          ~ views : HashMap<String, Double>
          + getMeasureValue()
          + setCredScore()
          + setImageUser()
          + setRankScore()
          + setUseRankScore()
          + setViews()
      }
    }
  }
  

  namespace rerank.cred {
    namespace exp {
      class rerank.cred.exp.CredRankerExp {
          ~ bulkProportion : HashMap<String, Double>
          ~ credConfig : Properties
          ~ credScore : HashMap<String, Double>
          ~ credScoreName : String
          ~ dataset : String
          ~ date : HashMap<String, String>
          ~ faceProportion : HashMap<String, Double>
          ~ imageUser : HashMap<String, String>
          ~ lat : HashMap<String, String>
          ~ latLongDataDir : String
          ~ locationSimilarity : HashMap<String, Double>
          ~ lon : HashMap<String, String>
          ~ meanImageTagClarity : HashMap<String, Double>
          ~ meanPhotoViews : HashMap<String, Double>
          ~ meanTagRank : HashMap<String, Double>
          ~ meanTagsPerPhoto : HashMap<String, Double>
          ~ meanTitleWordCounts : HashMap<String, Double>
          ~ measurer : CMeasurer
          ~ photoCount : HashMap<String, Double>
          ~ rand : Random
          ~ rankScore : HashMap<String, Double>
          ~ tagSpecificity : HashMap<String, Double>
          ~ time : HashMap<String, String>
          ~ uniqueTags : HashMap<String, Double>
          ~ uploadFrequency : HashMap<String, Double>
          ~ useRankScore : boolean
          ~ userCredFile : String
          ~ views : HashMap<String, Double>
          ~ visualScore : HashMap<String, Double>
          + run()
          - calRankScore()
          - computeLinearFusionCredScore()
          - getRandomValue()
          - getRankScoreByPosition()
          - invertScore()
          - normalizeMinMax()
          - reRankList()
          - readConfig()
          - readTopicImageUsers()
          - readUsersCred()
          - saveRankedList()
          - toDouble()
      }
    }
  }
  

  rerank.cred.exp.CMeasurer .up.|> IDigitalObjectDistanceMeasurer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
