@startuml

title __MMR's Class Diagram__\n

  namespace methods.mmr {
    class methods.mmr.MMR {
        ~ descriptorConfigFileName : String
        ~ diversityFactor : double
        ~ listDiverse : ArrayList<String>
        ~ listOriginal : ArrayList<String>
        ~ mmrConfigFile : String
        ~ reRankingDepth : int
        ~ topicsMap : String
        ~ topicsSize : String
        + MMR()
        + calcRelevancebyPosition()
        + run()
        - getObjectsRelevanceArray()
    }
  }
  

  namespace methods.mmr {
    class methods.mmr.MMRMinAverageDistanceMeasurer {
        + partialResult : ArrayList<DigitalObject>
        ~ diversityFactor : double
        ~ fm : FeatureManager
        ~ objectsRelevance : HashMap<String, Double>
        - numberOfDescriptors : int
        + MMRMinAverageDistanceMeasurer()
        + getMeasureValue()
        + setPartialResult()
        + setTarget()
    }
  }
  

  namespace methods.mmr {
    class methods.mmr.MMRMinMinDistanceMeasurer {
        + partialResult : ArrayList<DigitalObject>
        ~ diversityFactor : double
        ~ fm : FeatureManager
        ~ objectsRelevance : HashMap<String, Double>
        - numberOfDescriptors : int
        - target : ArrayList<DigitalObject>
        + MMRMinMinDistanceMeasurer()
        + getMeasureValue()
        + setPartialResult()
        + setTarget()
    }
  }
  

  methods.mmr.MMR .up.|> IDiversify
  methods.mmr.MMRMinAverageDistanceMeasurer .up.|> IDigitalObjectDistanceMeasurer
  methods.mmr.MMRMinMinDistanceMeasurer .up.|> IDigitalObjectDistanceMeasurer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
