@startuml

title __GENETICALGORITHM's Class Diagram__\n

  namespace methods.geneticAlgorithm {
    class methods.geneticAlgorithm.AverageLinkEvaluation {
        + runEvaluation()
        + runGAEvaluation()
        - getDistance()
    }
  }
  

  namespace methods.geneticAlgorithm {
    class methods.geneticAlgorithm.CentroidMethodEvaluation {
        + runEvaluation()
        + runGAEvaluation()
        - getDistance()
    }
  }
  

  namespace methods.geneticAlgorithm {
    class methods.geneticAlgorithm.CompleteLinkEvaluation {
        + runEvaluation()
        + runGAEvaluation()
        - getDistance()
    }
  }
  

  namespace methods.geneticAlgorithm {
    class methods.geneticAlgorithm.DaviesBouldinEvaluation {
        + runEvaluation()
        + runGAEvaluation()
        - getDistance()
        - getDistance()
    }
  }
  

  namespace methods.geneticAlgorithm {
    class methods.geneticAlgorithm.DiversifyGenerator {
        ~ jrand : int
        ~ oldrand : double[]
        ~ seed : double
        - rnd : Random
        + DiversifyGenerator()
        + DiversifyGenerator()
        + nextDouble()
        + nextInt()
        + rndInt()
        + rndReal()
        ~ advance_random()
        ~ randomize()
        ~ randomperc()
        ~ warmup_random()
    }
  }
  

  namespace methods.geneticAlgorithm {
    class methods.geneticAlgorithm.DiversifyPloblem {
        ~ dataset : String
        {static} ~ fitnessValue : Double
        ~ idLocal : int
        ~ inputList : ArrayList<DigitalObject>
        ~ locName : String
        ~ pathStorage : String
        - evaluationCriterion : int
        - evaluationLinkage : ELinkage
        - fm : FeatureManager
        - kClusters : int
        - linkage : ILinkage
        - linkageCriterion : int
        - originalList : ArrayList<DigitalObject>
        + DiversifyPloblem()
        + evaluate()
        + printChromosomeToFile()
        - initializeClustering()
        - mergeClusters()
        - readCluster()
        - runAgglomerativeClustering()
    }
  }
  

  namespace methods.geneticAlgorithm {
    interface methods.geneticAlgorithm.ELinkage {
        {abstract} + runEvaluation()
        {abstract} + runGAEvaluation()
    }
  }
  

  namespace methods.geneticAlgorithm {
    class methods.geneticAlgorithm.GAAlgorithm {
        ~ copyBest : int
        ~ dataset : String
        ~ generations : int
        ~ minConvergence : double
        + GAAlgorithm()
        + execute()
        + writeFitnessMeasures()
    }
  }
  

  namespace methods.geneticAlgorithm {
    class methods.geneticAlgorithm.GeneticAlgorithmMain {
        ~ alpha : String
        ~ configFileName : String
        ~ crossoverProbability : String
        ~ fm : FeatureManager
        ~ maxEvaluation : String
        ~ mutatedValue : String
        ~ mutationProbability : String
        ~ nBestIndividual : int
        ~ numberCopyBest : String
        ~ pathStorageSolutionSet : String
        ~ populationSize : String
        ~ seed : long
        ~ set : String
        ~ setSeed : boolean
        - convergence : double
        - evaluationCriterion : int
        - generations : int
        - indexPopulation : int
        - kClusters : int
        - linkage : ILinkage
        - linkageCriterion : int
        - numberFeatures : int
        + GeneticAlgorithmMain()
        + run()
        + writeFitnessMeasures()
        + writeNormalizedWeights()
        + writePopulationNormalized()
        - bestIndividualRun()
        - initializeClustering()
        - mergeClusters()
        - normalizeChromossome()
        - runAgglomerativeClustering()
    }
  }
  

  namespace methods.geneticAlgorithm {
    class methods.geneticAlgorithm.KMeansMethod {
        - CENTROIDS_INITIALIZER : int
        - CENTROIDS_UPDATE_METHOD : int
        - MAX_ITERATIONS : int
        - NUM_CLUSTERS : int
        - configFile : Properties
        - fm : FeatureManager
        - inputList : ArrayList<DigitalObject>
        - originalList : ArrayList<DigitalObject>
        - totNumIterations : int
        + getDistance()
        + run()
        + run()
        + setNUM_CLUSTERS()
        - runClustering()
        - selectInitialMedoids()
    }
  }
  

  namespace methods.geneticAlgorithm {
    class methods.geneticAlgorithm.MutationCreep {
        ~ seed : double
        {static} - VALID_TYPES : List
        - configFile : Properties
        - mutatedValue_ : Double
        - mutationProbability_ : Double
        + MutationCreep()
        + execute()
        - doMutation()
    }
  }
  

  namespace methods.geneticAlgorithm {
    class methods.geneticAlgorithm.RateDistanceIntraandInterclusterEvaluation {
        + runEvaluation()
        + runGAEvaluation()
        - getDistanceInter()
        - getDistanceIntra()
    }
  }
  

  namespace methods.geneticAlgorithm {
    class methods.geneticAlgorithm.SilhouetteEvaluation {
        + runEvaluation()
        + runGAEvaluation()
        - getDistance()
        - getDistanceGA()
        - maximumDissimilarityCluster()
        - maximumDissimilarityClusterGA()
        - silhouetteAVGToCluster()
        - silhouetteAVGToClusterGA()
    }
  }
  

  namespace methods.geneticAlgorithm {
    class methods.geneticAlgorithm.SingleLinkEvaluation {
        + runEvaluation()
        + runGAEvaluation()
        - getDistance()
    }
  }
  

  namespace methods.geneticAlgorithm {
    class methods.geneticAlgorithm.SumSquaredErrorEvaluation {
        + runEvaluation()
        + runGAEvaluation()
        - getDistance()
    }
  }
  

  namespace methods.geneticAlgorithm {
    class methods.geneticAlgorithm.WardsEvaluation {
        + getDistance()
        + runEvaluation()
        + runGAEvaluation()
    }
  }
  

  methods.geneticAlgorithm.AverageLinkEvaluation .up.|> ELinkage
  methods.geneticAlgorithm.CentroidMethodEvaluation .up.|> ELinkage
  methods.geneticAlgorithm.CompleteLinkEvaluation .up.|> ELinkage
  methods.geneticAlgorithm.DaviesBouldinEvaluation .up.|> ELinkage
  methods.geneticAlgorithm.DiversifyGenerator .up.|> IRandomGenerator
  methods.geneticAlgorithm.GeneticAlgorithmMain .up.|> IDiversify
  methods.geneticAlgorithm.KMeansMethod .up.|> IDiversify
  methods.geneticAlgorithm.RateDistanceIntraandInterclusterEvaluation .up.|> ELinkage
  methods.geneticAlgorithm.SilhouetteEvaluation .up.|> ELinkage
  methods.geneticAlgorithm.SingleLinkEvaluation .up.|> ELinkage
  methods.geneticAlgorithm.SumSquaredErrorEvaluation .up.|> ELinkage
  methods.geneticAlgorithm.WardsEvaluation .up.|> ELinkage


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
