@startuml

title __CREDIBILITY's Class Diagram__\n

  namespace methods.credibility {
    class methods.credibility.CredibilityClustering {
        ~ bulkProportion : HashMap<String, Double>
        ~ clusterMethod : int
        ~ credConfig : Properties
        ~ credScore : HashMap<String, Double>
        ~ dataset : String
        ~ faceProportion : HashMap<String, Double>
        ~ intraSortByViews : boolean
        ~ latLongDataDir : String
        ~ locationSimilarity : HashMap<String, Double>
        ~ meanImageTagClarity : HashMap<String, Double>
        ~ meanPhotoViews : HashMap<String, Double>
        ~ meanTagRank : HashMap<String, Double>
        ~ meanTagsPerPhoto : HashMap<String, Double>
        ~ meanTitleWordCounts : HashMap<String, Double>
        ~ metadata : HashMap<String, ImgMetadata>
        ~ photoCount : HashMap<String, Double>
        ~ rankScore : HashMap<String, Double>
        ~ tagSpecificity : HashMap<String, Double>
        ~ uniqueTags : HashMap<String, Double>
        ~ uploadFrequency : HashMap<String, Double>
        ~ useRankScore : boolean
        ~ userCredFile : String
        ~ users : ArrayList<String>
        ~ visualScore : HashMap<String, Double>
        - originalList : ArrayList<DigitalObject>
        + run()
        - clusterByMonth()
        - clusterByUser()
        - clusterByUserAndMonth()
        - intraSortByViews()
        - readConfig()
        - readTopicImageUsers()
        - readUserList()
        - runCredibilityClustering()
    }
  }
  

  methods.credibility.CredibilityClustering .up.|> IDiversify


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
