@startuml

title __AGGLOMERATIVE's Class Diagram__\n

  namespace methods.agglomerative {
    class methods.agglomerative.AgglomerativeClustering {
        - configFile : Properties
        - fm : FeatureManager
        - kClusters : int
        - linkage : ILinkage
        - linkageCriterion : int
        - originalList : ArrayList<DigitalObject>
        + run()
        + run2()
        + runForEnsemble()
        + separator()
        + setNUM_CLUSTERS()
        - initializeClustering()
        - mergeClusters()
        - runAgglomerativeClustering()
    }
  }
  

  namespace methods.agglomerative {
    class methods.agglomerative.AverageLink {
        + findClosestPair()
        + findClosestPair()
        + getDistance()
        - getDistance()
    }
  }
  

  namespace methods.agglomerative {
    class methods.agglomerative.CentroidMethod {
        + findClosestPair()
        + findClosestPair()
        + getDistance()
        + getDistance()
    }
  }
  

  namespace methods.agglomerative {
    class methods.agglomerative.CompleteLink {
        + findClosestPair()
        + findClosestPair()
        + getDistance()
        - getDistance()
    }
  }
  

  namespace methods.agglomerative {
    interface methods.agglomerative.ILinkage {
        {abstract} + findClosestPair()
        {abstract} + findClosestPair()
        {abstract} + getDistance()
    }
  }
  

  namespace methods.agglomerative {
    class methods.agglomerative.MedianMethod {
        + findClosestPair()
        + findClosestPair()
        + getDistance()
        - getDistance()
    }
  }
  

  namespace methods.agglomerative {
    class methods.agglomerative.SingleLink {
        + findClosestPair()
        + findClosestPair()
        + getDistance()
        - getDistance()
    }
  }
  

  namespace methods.agglomerative {
    class methods.agglomerative.WardsMethod {
        + findClosestPair()
        + findClosestPair()
        + getDistance()
        - getDistance()
    }
  }
  

  methods.agglomerative.AgglomerativeClustering .up.|> IDiversify
  methods.agglomerative.AverageLink .up.|> ILinkage
  methods.agglomerative.CentroidMethod .up.|> ILinkage
  methods.agglomerative.CompleteLink .up.|> ILinkage
  methods.agglomerative.MedianMethod .up.|> ILinkage
  methods.agglomerative.SingleLink .up.|> ILinkage
  methods.agglomerative.WardsMethod .up.|> ILinkage


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
